version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_catalog
    ports:
      - "3307:3306"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  product-catalog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/product_catalog
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/product_catalog
